wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1693898842.665532
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.10
      5: 0.14.0
      8:
      - 1
      - 5
consequent_value:
  desc: null
  value: alarma
fitness_function:
  desc: null
  value: composed_fitness_length_fitness
generation_size:
  desc: null
  value: 200
mutation_probability:
  desc: null
  value: 0.001
num_generations:
  desc: null
  value: 100
probability_of_zero:
  desc: null
  value: 0.6
seed:
  desc: null
  value: 43
