wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.2
    start_time: 1679866513.76652
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.11.2
      5: 0.14.0
      8:
      - 5
consequent_value:
  desc: null
  value: financia
fitness_function:
  desc: null
  value: composed_fitness_length_fitness
generation_size:
  desc: null
  value: 500
mutation_probability:
  desc: null
  value: 0.001
num_generations:
  desc: null
  value: 1000
probability_of_zero:
  desc: null
  value: 0.6
seed:
  desc: null
  value: 43
